//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookInventory()
        {
            this.CheckOut = new HashSet<CheckOut>();
        }
    
        public int Inventory_ID { get; set; }
        public int BookID { get; set; }
        public int LibraryCopy_ID { get; set; }
        public string Avaliable { get; set; }
        public System.DateTime Inventory_Date { get; set; }
    
        public virtual LibraryBooks LibraryBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckOut> CheckOut { get; set; }
    }
}
