//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int CheckOut_ID { get; set; }
        public int Inventory_ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CheckOut_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
        public Nullable<System.DateTime> Actual_Return_Date { get; set; }
    
        public virtual BookInventory BookInventory { get; set; }
        public virtual LibraryUsers LibraryUsers { get; set; }
    }
}
